replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "dnason/kbot"
  tag: "v1.0.4-e2a9b48"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "key"
securityContext:
  privileged: true
