replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "dnason/kbot"
  tag: "1.0.3-6cdf938"
  arch: amd64
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "key"
securityContext:
  privileged: true
